version: "3.8"

# define our services
services: 
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - type: volume
        source: db
        target: /data
        volume:
          nocopy: true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - shared-network
  server:
    container_name: auth_server
    restart: unless-stopped
    image: server
    env_file:
      - ./.env
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - secretOrKey=$secretOrKey
    networks:
      - shared-network
    depends_on:
      - mongodb
  client:
    container_name: auth_client
    restart: unless-stopped
    image: client
    env_file:
      - ./.env
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    networks:
      - shared-network
    depends_on:
      - server

networks:
  shared-network:

volumes:
  db:
