import Head from 'next/head'
import React from 'react'
import { Features, Hero, Navbar } from '../components'

class Home extends React.Component {
  render() {
    return (
      <div>
        <Head>
          <title>Node-Auth</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero />
        <Features />
        
      </div>
    )
  }
}

export default Home
