import type { NextPage } from 'next'
import Head from 'next/head'
import { Hero } from '../components'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Node-Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center">
        <Hero />
      </div>
      
    </div>
  )
}

export default Home
